### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by ghost** [rickymarcon/homebridge-daikin#2]
Hi, I have installed the UUID and added https:// to the config...
I have the BRP072C42 fw ver 1.13.7
Hoping you can shed some light on this error please.
Thanks in advance!

(node:96031) UnhandledPromiseRejectionWarning: StatusCodeError: 403 - ""
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/request-promise-core/lib/errors.js:32:15)
    at /usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/request-promise-core/lib/plumbing.js:97:41
    at tryCatcher (/usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-daikin-unofficial/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
(node:96031) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:96031) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ghost** [comment]
My bad. I left the dashes in the UUID in the config.json
